// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 5,
  "totalRatings": 35,
  "reviews": [
    {
      "author": "Lisa Akar",
      "rating": 5,
      "text": "Wir haben das Team von Haus & Gartenservice Pilavdzic mit dem Anlegen unserer Terasse beauftragt und sind sehr zufrieden mit dem Ergebnis. Die Beratung, Planung und Umsetzung war unkompliziert, freundlich und kompetent. Können wir nur empfehlen!",
      "time": "vor 3 Jahren"
    },
    {
      "author": "Vanessa Albert",
      "rating": 5,
      "text": "Das Team vom Haus & Gartenservice Pilavdzic hat unserer Garage zu neuem Glanz verholfen. Wir sind sehr zufrieden mit der netten Beratung, der schnellen Umsetzung und den fairen Konditionen. Einfach empfehlenswert! Wir werden auch zukünftig gerne auf ihren Service zurückgreifen.",
      "time": "vor 4 Jahren"
    },
    {
      "author": "Gudrun von Thun-Blaul",
      "rating": 5,
      "text": "Nachdem unser bisheriger Gärtner betriebsbedingt aufhörte, fand ich per Internet die Firma Pilavdcic. Ich bekam schnell einen sehr freundlichen Rückruf, Herr Pilavdcic besichtigte sehr kurzfristig das zu bearbeitende Areal, erstellte ein sehr faires Angebot und erledigte den Auftrag zur größten Zufriedenheit. Aus meiner Familie erhält er weitere Aufträge.",
      "time": "vor einem Jahr"
    },
    {
      "author": "Frank Peter",
      "rating": 5,
      "text": "Ich muss sagen das ich von Anfang bis Ende vollsten zufrieden war. Angefangen mit dem 1. Gespräch bis hin zu verlassen der Baustelle die top sauber war. Super netter Chef mit Prima Ideen die letztendlich  während der Bauphase weiter entwickelt wurde um meine Terrasse noch besser und g.rößer zu gestalten als an Anfang. Das fand ich spitze das sich da noch Gedanken gemacht wurde. Die Arbeiter haben super Arbeit geleistet und sind sehr zuvor kommend. Einfach nur Top. Kann ich nur weiter empfehlen. Schön das es so Firmen gibt. Weiter so...",
      "time": "vor 3 Jahren"
    },
    {
      "author": "Rosemarie Friedel",
      "rating": 5,
      "text": "wir haben unseren Garten von der Firma Garten- und Landschaftsbau Pilavdzic neu anlegen lassen und sind rundum begeistert. Der Kontakt war mehr als sehr angenehm. Die Arbeiter sind top  motiviert, interessiert an ihrer Arbeit und haben mit viel Sorgfalt und Freude gearbeitet. Alles lief zügig,  pünktlich, sauber und ordentlich ab. Wir sind in jeder Hinsicht sehr zufrieden und können die Firma nur wärmstens weiterempfehlen. Vielen Dank für die tolle Arbeit.",
      "time": "vor 10 Monaten"
    }
  ]
};
